import type { LText } from "@/lib/i18n";
import LABS from "@/data/en-kmitl/compro/labs.json";

/**
 * ComPro (EN-KMITL) lab bank — chapters 1–5 of the course portal, presented
 * as weeks 1–5.
 *
 * The JSON is generated by scripts/build_compro_labs.py; do not hand-edit it.
 * Every case in it was recovered from the portal's merged terminal transcript
 * and then re-verified by piping the recovered stdin through the reference
 * solution in a real CPython subprocess, so `expected` is the byte-exact
 * stdout a correct program produces — see that script's header for the method.
 */

export interface ComProCase {
  id: string;
  /** Lines fed to stdin, newline-separated, with no trailing newline. */
  stdin: string;
  /** Byte-exact stdout, with the trailing newline stripped. */
  expected: string;
}

export interface ComProProblem {
  /** "ch3-4" — stable across regeneration, used as the localStorage key. */
  id: string;
  week: number;
  item: number;
  title: string;
  /** Problem statement as published by the portal (Thai, with code fences). */
  descriptionMd: string;
  /** A solution the portal graded 2/2, with its submission header stripped. */
  reference: string;
  cases: ComProCase[];
}

export interface ComProWeek {
  week: number;
  chapterTitle: string;
  titleTh: string;
  focusTh: string;
}

export const COMPRO_WEEKS: ComProWeek[] = LABS.weeks;
export const COMPRO_PROBLEMS: ComProProblem[] = LABS.problems;
export const COMPRO_META = LABS.meta;

/** Portal marking: every item is worth 2 points, 5 items per chapter. */
export const POINTS_PER_PROBLEM = 2;
export const COMPRO_TOTAL_POINTS = COMPRO_PROBLEMS.length * POINTS_PER_PROBLEM;

export function problemsForWeek(week: number): ComProProblem[] {
  return COMPRO_PROBLEMS.filter((p) => p.week === week);
}

export function findProblem(id: string): ComProProblem | undefined {
  return COMPRO_PROBLEMS.find((p) => p.id === id);
}

/**
 * House rules the hub grades against, shown above the editor.
 *
 * The first two are how the portal's own judge behaves, restated for students
 * who have only ever seen their code "look right" in a terminal. The import
 * rule is a house rule rather than a quoted regulation: chapters 1–5 teach
 * builtins only, and all 25 graded reference solutions use zero imports, so
 * the hub flags an import as out-of-scope for the week rather than blocking
 * the run.
 */
export const COMPRO_RULES: { title: LText; detail: LText }[] = [
  {
    title: {
      th: "ผลลัพธ์ต้องตรงทุกตัวอักษร",
      en: "Output must match exactly",
    },
    detail: {
      th: "เทียบแบบตัวต่อตัว เว้นวรรคเกิน 1 ช่อง ตัวพิมพ์ใหญ่-เล็กไม่ตรง หรือลืมจุดท้ายประโยค = ไม่ผ่าน",
      en: "Compared character by character. One extra space, a wrong case, or a missing period fails the case.",
    },
  },
  {
    title: {
      th: "ข้อความ prompt นับเป็นผลลัพธ์ด้วย",
      en: "Prompt text counts as output",
    },
    detail: {
      th: "ข้อความใน input(\"...\") ถูกพิมพ์ออกจอ จึงต้องสะกดให้ตรงตามโจทย์ รวมช่องว่างหน้า-หลังเครื่องหมาย :",
      en: "The string inside input(\"...\") is printed, so it must match the problem exactly, spaces included.",
    },
  },
  {
    title: {
      th: "สัปดาห์ 1–5 ใช้เฉพาะคำสั่งพื้นฐาน ห้าม import",
      en: "Weeks 1–5 are builtins only — no imports",
    },
    detail: {
      th: "ยังไม่ได้เรียน module — ใช้ print, input, int, float, str, abs, range, chr, ord และตัวดำเนินการเท่านั้น",
      en: "Modules are not taught yet — use print, input, int, float, str, abs, range, chr, ord and operators only.",
    },
  },
];

/** Lines that would break the no-import rule, for the pre-run check. */
export function findImports(code: string): { line: number; text: string }[] {
  const hits: { line: number; text: string }[] = [];
  code.split("\n").forEach((raw, i) => {
    // Strip string literals and comments first so an "import" inside printed
    // text (chapter 1's reserved-words list prints the word) is not flagged.
    const stripped = raw
      .replace(/"""[\s\S]*?"""|'''[\s\S]*?'''/g, "")
      .replace(/"(?:[^"\\]|\\.)*"|'(?:[^'\\]|\\.)*'/g, "")
      .replace(/#.*$/, "");
    if (/^\s*(?:import\s+\S|from\s+\S+\s+import\s)/.test(stripped)) {
      hits.push({ line: i + 1, text: raw.trim() });
    }
  });
  return hits;
}
